# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana:6.5.0

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
ADD config/kibana.yml /usr/share/kibana/config

